[book]
authors = ["Fanda Vacek"]
language = "en"
multilingual = false
src = "src"
title = "SHV RPC Documentation"

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
[output.linkcheck]
