[book]
authors = ["Fanda Vacek"]
language = "en"
src = "src"
title = "SHV RPC Documentation"

[preprocessor.pagetoc]

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
git-branch = "master"

[output.html]
additional-css = ["theme/pagetoc.css", "theme/open-in.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/silicon-heaven/shv-doc"
[output.linkcheck2]
